version: "3.9"

networks:
  dev:
    driver: bridge

services:
  api:
    container_name: CleanArchApi
    build: 
        context: ./CleanArchitecture
        dockerfile: Dockerfile
    depends_on: 
      - "db"
      #- "reverse_proxy"
    ports:
      - "8000:80"
    networks:
      - dev
  #reverse_proxy:
  #  image: nginx:alpine
  #  container_name: CleanArchReverseProxy
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #  ports:
  #    - "4000:4000"
  #  networks:
  #    - dev
  db:
    image: postgres:14.1-alpine
    container_name: CleanArchDb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Margoleta16!
      - POSTGRES_DB=CleanArch
    ports:
      - '5432:5432'
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev
  redis:
    image: "redis:alpine"
    container_name: CleanArchRedis
    ports:
      - "6379:6379"
volumes:
  pgdata: