version: "3.9"
services:
  web:
    build: ./WebApi
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT = "Development"
      - APP_CONTENT_ROOT = ""
      - APP_WEB_ROOT = ""
      - ACTIVE_CONNECTION_VARIABLE = "PgSQLConnection"
      - ACTIVE_SCHEMA_VARIABLE = "PgSQLConnection"